# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
