# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpoint', '0002_auto_20190306_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='none', upload_to='island_images'),
        ),
        migrations.AddField(
            model_name='destination',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='destination',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default='none', unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
