# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpoint', '0003_auto_20190312_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='destination',
            name='budget',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='climate',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
